#!/usr/bin/env bash

SESSION_FILE='./session.txt'

DAY="$(date +%-d)"
YEAR="$(date +%Y)"

if [[ ! -z "$1" ]]; then
  DAY="$1"
fi

if [[ ! -z "$2" ]]; then
  YEAR="$2"
fi

if [[ ! -f "$SESSION_FILE" ]]; then
  echo -n <<SESSION_INFO
  You must create a file called \`session.txt'.
  It has to contain the value of the session cookie from Advent of Code.
SESSION_INFO

  exit 1
fi

COOKIE_VALUE="session=$(cat "$SESSION_FILE" | tr -d '\n')"

echo "Getting problem for day $DAY/$YEAR"
curl \
  -sL \
  --fail \
  --cookie "$COOKIE_VALUE" \
  "https://adventofcode.com/$YEAR/day/$DAY/input" \
  -o "./inputs/$DAY"

[ $? -ne 0 ] && exit

curl \
  -sL \
  --fail \
  "https://adventofcode.com/$YEAR/day/$DAY" |
  pup --plain 'pre > code json{}' |
  jq -r '.[0].text' \
    >"./inputs/$DAY.test"
